"""1. Створити функцію, що приймає число з консолі (використати функцію input());
    Функція повинна обробити значення таким чином: використовуючи вбудовану функцію int(),
    спробувати конвертувати рядок в число (input() завжди повертає рядок).
    Якщо конвертувати не виходить, то вивести в консоль "Entered not valid data"."""


def some_of_line():
    number = input()
    try:
        int(number)
    except ValueError:
        print("Entered not valid data")


# some_of_line()
#
#
# """2. Створити функцію, що приймає 2 рядки;
#     Якщо хоча б один рядок не виходить конвертувати в число, тоді робимо конкатенацію (з'єднуємо рядки),
#     якщо ж обидва значення можна конвертувати в числа, то отримуємо їх суму.
#     Результат друкуємо в консоль."""


def func2():
    a = input("Enter first value")
    b = input("Enter second value")
    try:
        x = int(a)
        y = int(b)
        result = x + y
    except ValueError:
        result = a + b
    print(result)


# func2()


#
# """3. Створити функцію, що приймає значення з консолі. Якщо значення не можна привести до числа,
#     тоді просимо користувача ввести інше значення, доки він не введе число. Згадуємо про цикл while.
#    Коли користувач вводить число, дякуємо йому!"""

def func3():
    while True:
        a = input("Enter first value")
        try:
            int(a)

        except ValueError:
            print("Введіть інше число будь ласка")
        else:
            print(f'Дякую, ви ввели число {a}')
            break
        finally:
            print("Дякую за увагу")


# func3()


#
# """4. Створити ВЛАСНЕ виключення. Наприклад OnlyEvenError. Створити функцію check_digit(), яка приймає число.
#         Якщо число не парне, то породжувати це своє виключення;
#         Якщо парне, то повертати його (return)"""
#
class OnlyEvenError(IndexError):
    pass


def check_digit(n):
    if n % 2 != 0:
        raise OnlyEvenError("Це число не парне, то породжує своє виключення")
    else:
        print(f'Ви ввели число {n}')
        return n



# """5. Створити функцію, що буде приймати число як аргумент і викликАти в тілі функцію check_digit,
#         в яку передавати це число.
#        Якщо виникає помилка, то перехопити її, та збільшити вхідне число на 1;
#        Якщо помилки не вникає, то помножити число на 2.
#         Результат виводити в консоль.
#         Також функція повинна надрукувати в консоль фразу "Я все одно завжди щось друкую".
#        !!! Використовувати try-except-else-finally"""
#
def check_digit2(n):
    try:
       check_digit(n)
    except OnlyEvenError:
        result = n + 1
    else:
        result = n * 2
    finally:
        print("Я все одно завжди щось друкую")
    return result

print(check_digit2(3))


